Update Chinese translation
fluidd-core/fluidd pull request #1106
Opened 2023-05-30 14:57 UTC by ptsa

Update Chinese translation

2023-05-30 15:15 UTC, ptsa commented
> Thank you @ptsa, can you please add a footer to the main PR comment with a "Signed-off-by" line, following the [CONTRIBUTING](https://github.com/fluidd-core/fluidd/blob/develop/CONTRIBUTING.md) guidelines.
> 
> Thank you!

Signed-off-by: Ptsa [Ptsa1987@gmail.com](mailto:Ptsa1987@gmail.com) 
have updated

2023-06-01 08:24 UTC, pedrolamas requested changes

2023-06-01 08:24 UTC, pedrolamas commented on src/locales/zh-CN.yaml
> +      active:
Translation missing here

2023-06-01 08:31 UTC, pedrolamas approved these changes

2023-06-01 08:31 UTC, ptsa commented on src/locales/zh-CN.yaml
> +      active:
Fixed

2023-06-04 14:33 UTC, matmen approved these changes

2023-06-04 14:37 UTC, merged