feat(i18n-SL): Update Slovenian translations
fluidd-core/fluidd pull request #1329
Opened 2024-01-29 08:34 UTC by jernejp21

Updated Slovenian translations to the latest version - from day 2024-01-29.

2024-02-03 20:18 UTC, matmen requested changes
Thanks for your translations. They look good to me content-wise, there's just one small formatting inconsistency:

2024-02-03 20:18 UTC, matmen commented on src/locales/sl.yaml
> +      multiply_job: Podvoji opravilo |Podvoji opravila
```suggestion
      multiply_job: Podvoji opravilo | Podvoji opravila
```

2024-02-05 14:01 UTC, jernejp21 commented on src/locales/sl.yaml
> +      multiply_job: Podvoji opravilo |Podvoji opravila
Thank you for the check.

2024-02-05 14:16 UTC, pedrolamas approved these changes

2024-02-05 15:14 UTC, matmen approved these changes

2024-02-05 15:15 UTC, merged