Russian translation update
fluidd-core/fluidd pull request #1413
Opened 2024-04-12 07:48 UTC by AndylgTom

Russian translation update. 
It was tested on a local development server. The translation is based on the latest version of en.yaml. 
Thx.

2024-04-26 18:27 UTC, pedrolamas approved these changes

2024-04-27 09:48 UTC, pedrolamas requested changes
Thank you @AndylgTom, can you please add a footer to the main PR comment with a "Signed-off-by" line, following the [CONTRIBUTING](https://github.com/fluidd-core/fluidd/blob/develop/CONTRIBUTING.md) guidelines.

2024-04-27 14:56 UTC, AndylgTom commented
> Thank you @AndylgTom, can you please add a footer to the main PR comment with a "Signed-off-by" line, following the [CONTRIBUTING](https://github.com/fluidd-core/fluidd/blob/develop/CONTRIBUTING.md) guidelines.

Done.

2024-04-27 15:00 UTC, pedrolamas approved these changes

2024-04-28 10:23 UTC, merged