feat: Mellow theme
fluidd-core/fluidd pull request #1472
Opened 2024-08-07 07:27 UTC by exiom-xyz

Add Mellow theme for Community Preset
Thanks!

2024-11-14 09:36 UTC, pedrolamas requested changes

2024-11-14 09:36 UTC, pedrolamas commented on public/logo_mellow.svg
> +  <image width="2354" height="1835" xlink:href="data:img/png;base64,iVBORw0KGgoAAAANSUhEUgAAAOsAAAC4CAYAAAACEBuMAAAfxklEQVR4nO1dB9AVRRIeQDIokhFRUYyYM+Ys5pwOFQMmzGf2zIrhlHCnnlkwZ/TMmEU5EwbAhHdGVBSUX/1
This is not a proper vectorial SVG, just a PNG encapsulated inside the SVG code.

We need a proper vectorial SVG image to make sure it shows correctly with any screen resolution.

2024-11-15 10:39 UTC, pedrolamas approved these changes

2024-11-18 07:26 UTC, matmen approved these changes
@pedrolamas Do we have permission to use their logo? If we do then this LGTM

2024-11-18 09:10 UTC, pedrolamas commented
> @pedrolamas Do we have permission to use their logo? If we do then this LGTM

They got in touch with me via email and I got them confirming we can use the logo, so I think we are good!

2024-11-18 09:16 UTC, merged