Documentation about configuring multiple cameras
fluidd-core/fluidd pull request #455
Opened 2021-12-05 23:20 UTC by derlaft

Current documentation says to check `cameras.md` for info about configuring multiple cameras.

However, there isn't much of it. This commit tries to address it, documenting the process of configuring multiple mjpeg_streamer instances.
 
Signed-off-by: Aleksei Kharlamov <der@2-47.ru>

2021-12-09 12:02 UTC, sjqlwy approved these changes
nice work, details can be found on https://docs.mainsail.xyz/quicktips/multicam

2021-12-09 12:05 UTC, derlaft commented
Huh, that's a much better version of what I was trying to create, really regret not finding that myself :) Probably makes no sense to use this version since a superior one already exists

2022-01-26 21:12 UTC, eduncan911 commented
> Huh, that's a much better version of what I was trying to create, really regret not finding that myself :) Probably makes no sense to use this version since a superior one already exists

@sjqlwy @derlaft, should we link to Mainsail's document?

@pedrolamas, is there a precedence of linking to Mainsail for documents and config settings?  If not, then perhaps we do keep this file and add a bunch of info to it?

2022-01-26 21:16 UTC, derlaft commented
> is there a precedence of linking to Mainsail for documents and config settings? If not, then perhaps we do keep this file and add a bunch of info to it?

Both projects are GPL, you can just copy mainsail docs into here.

2022-01-26 21:23 UTC, eduncan911 commented
> > is there a precedence of linking to Mainsail for documents and config settings? If not, then perhaps we do keep this file and add a bunch of info to it?
> 
> Both projects are GPL, you can just copy mainsail docs into here.

Lol, true... But that just feels, wrong.  Heh.

2022-01-27 13:05 UTC, pedrolamas commented
> @pedrolamas, is there a precedence of linking to Mainsail for documents and config settings? If not, then perhaps we do keep this file and add a bunch of info to it?

No idea...

Having said that, I don't think it is a big issue to copy and adapt Mainsail docs to here.

In the end of the day, we are all working in benefit of the Klipper user-community and we should have as much alignment on documentation of shared features/functionality as possible.

In any case, I think it best to just drop a message to Mainsail mods just to make they do agree with this view.

2022-01-27 15:03 UTC, eduncan911 commented
@derlaft could you reach out to some Mailsail devs on their chat/discord/etc and see if they are fine with replicating some documentation between the projects?

2022-02-22 14:49 UTC, pedrolamas submitted a review, later dismissed
LGTM

2022-02-22 19:24 UTC, matmen requested changes

2022-02-22 19:24 UTC, matmen commented on docs/features/cameras.md
> +1. Copy `webcam.txt` configuration file into a new one
```suggestion
1. Copy the `webcam.txt` configuration file into a new one 
```

2022-02-22 19:24 UTC, matmen commented on docs/features/cameras.md
> +   matching `webcam*.txt` wildcard.
```suggestion
   matching the `webcam*.txt` wildcard.
```

2022-02-22 19:24 UTC, matmen commented on docs/features/cameras.md
> +   Make sure each configuration file to a different camera.
```suggestion
   Make sure each configuration file points to a different camera.
```

2022-02-22 19:24 UTC, matmen commented on docs/features/cameras.md
> +   `camera_http_options` parameter.
```suggestion
   the `camera_http_options` parameter.  
```

2022-02-22 19:24 UTC, matmen commented on docs/features/cameras.md
> +4. Restart webcamd via SSH: `sudo systemctl restart webcamd`.
webcamd can now also be restarted using the UI:
```suggestion
4. Restart webcamd either via the tools drawer in the top right of the UI
   or via SSH: `sudo systemctl restart webcamd`.
```

2022-02-22 20:59 UTC, pedrolamas approved these changes

2022-02-22 21:03 UTC, matmen approved these changes

2022-02-22 21:11 UTC, merged