chore: Adjust page title order when printing
fluidd-core/fluidd pull request #493
Opened 2022-01-29 12:03 UTC by ChipCE

Currently, when printing the page title is in <code>`${instanceName} | ${pageName} | [${this.progress}%]`</code> format with the display result is <code>[Percent ring icon] MyPrinterName | Dashboard | xx%</code>. Due to the long title string, the percent number more likely to be trimmed down due to the width limit of browser tab. There is percent ring icon, but it's hard to tell the real number and progress, specially on long print.
By moving the percent number to the front (<code>[Percent ring icon] xx% | MyPrinterName | Dashboard</code>), it will make user easier to have quick glance about the print process without have to switch thru tabs. It's not a big impact on user with a single printer, but for people with multi instance of fluidd running (farm for example), I think this change will help the manage job easier.

Signed-off-by: John Smith <login721@gmail.com>

2022-02-01 14:45 UTC, shinuza commented
Hi thanks for your contribution. This is a good idea but a tad opinionated, maybe we could offer multiple options and in a future revision offer a template with variable substitution. @StuSerious What do you think?

2022-02-01 19:47 UTC, matmen requested changes

2022-02-01 19:47 UTC, matmen commented on src/App.vue
> +      return `[${this.progress}%] | ${instanceName} | ${pageName} | [${this.progress}%]`
the other ` | [${this.progress}%]` can probably be removed, no?

2022-02-01 23:53 UTC, ChipCE commented
@matmen Oups, sorry! 
Fixed it.

2022-02-02 10:45 UTC, pedrolamas commented
Personally, I like this change, but will wait for further comments from other users.

@shinuza makes a good point of having this as a configurable setting, but in the end I do think it would be more useful and simpler to have it only as the proposed implementation in this PR.

2022-02-08 10:18 UTC, shinuza commented
I'd say we should merge this and then add the option to change it in options if people want the old behavior back 😄

2022-02-08 22:07 UTC, shinuza approved these changes
LGTM.

2022-02-08 22:15 UTC, pedrolamas approved these changes

2022-02-09 09:22 UTC, merged