Pause autoscroll when back scrolling
fluidd-core/fluidd pull request #495
Opened 2022-01-29 23:51 UTC by randellhodges

When scrolled up, it will "pause" the auto scroll to bottom until you scroll down or click the button to scroll back to the bottom. The button will only be displayed when scrolling is "paused".

This is for https://github.com/fluidd-core/fluidd/issues/343

This was lightly tested with Firefox and Edge in Ubuntu.  Additional testing would be appreciated.

2022-02-16 16:46 UTC, pedrolamas requested changes
There seems to be a styling/layout issue here, as the new "scroll to bottom" button is bigger than the existing ones:

![image](https://user-images.githubusercontent.com/85504/154314261-db5c8579-0789-489e-bf3a-534fa83e0562.png)

2022-02-16 17:06 UTC, pedrolamas commented on src/components/widgets/console/ConsoleCard.vue
> +      </v-tooltip>
From my understanding, the `app-btn` is the preferred way to get this button here:

```suggestion

      <app-btn
        v-if="scrollingPaused"
        @click="console.scrollToBottom(true)"
        color=""
        fab x-small text>
        <v-icon>$down</v-icon>
      </app-btn>
```

2022-02-17 18:52 UTC, pedrolamas commented
I've fixed the layout issues using the proposed solution!

2022-02-17 18:52 UTC, pedrolamas approved these changes

2022-02-18 17:06 UTC, matmen approved these changes

2022-02-18 17:06 UTC, merged