Gcode Preview - support delta kinematics
fluidd-core/fluidd pull request #591
Opened 2022-03-18 09:00 UTC by susisstrolch

Signed-off-by: Juergen Orschiedt <juorschiedt@gmail.com>

2022-03-18 09:34 UTC, pedrolamas requested changes

2022-03-18 09:34 UTC, pedrolamas commented on src/components/widgets/gcode-preview/GcodePreview.vue
> +    return this.$store.getters['printer/getPrinterSettings']('printer.kinematics') === 'delta'
I believe your changes should work with both `delta` and `rotary_delta`, so can you make sure you check for both?

2022-03-18 11:07 UTC, susisstrolch commented
Even I've added a test for "rotary_delta" I'm not sure it will work out.
I simply don't know how to compute the bedsize for a rotary.
So I'd suggest to omit the "rotary_delta" for the moment until we get a clear description how the bedsize (radius) is computed.

2022-03-18 11:23 UTC, pedrolamas commented
> So I'd suggest to omit the "rotary_delta" for the moment until we get a clear description how the bedsize (radius) is computed.

That is fair and makes sense! Let us then wait for someone with such a printer to do that bit!

2022-03-18 11:33 UTC, pedrolamas submitted a review, later dismissed
LGTM

2022-03-18 11:39 UTC, susisstrolch commented
The current implementation doesn't hurt so much, because print radius will be preset with 100.0 for rotary_delta.
However we could add an additional printer_radius setting for those who want to have an exact picture.

2022-03-18 11:53 UTC, pedrolamas commented
> The current implementation doesn't hurt so much, because print radius will be preset with 100.0 for rotary_delta. However we could add an additional printer_radius setting for those who want to have an exact picture.

My personal knowledge on how a delta works is quite limited so I can't evaluate exactly what this involves.

If this works with your delta, I'm happy to merge the changes, as code-wise, this looks perfect to me and I've regression tested this to make sure everything is fine!

2022-03-18 12:06 UTC, susisstrolch commented
Ok, so let's go on and let's wait for the rotary_delta guys...

2022-03-18 21:53 UTC, matmen approved these changes
LGTM overall, just one tiny thing I would change ;)

2022-03-18 21:53 UTC, matmen commented on src/components/widgets/gcode-preview/GcodePreview.vue
> +    if (this.isDelta) {
This branch could be moved before `const transform = ...` to save a memory allocation for an unused reference

2022-03-19 09:55 UTC, pedrolamas approved these changes

2022-03-19 12:50 UTC, matmen approved these changes
LGTM, just waiting for a delta user to chime in..

2022-03-19 13:57 UTC, merged