Update Hungarian language
fluidd-core/fluidd pull request #640
Opened 2022-04-23 06:51 UTC by AntoszHUN

Sorry to update again. I also found several errors and translation errors. True, this makes it harder to find errors that the web interface hasn’t been updated, and I don’t see what screen the caption or text is associated with.

  - Fixed several minor bugs.
  - Insert and translate missing text elements.
  - Full file scan.
  - Check for line breaks.
  - Check and compare end-of-sentence punctuation with the original language (en.yaml) file.
  - Improve spelling.

Thank you for your understanding. The next fix will only be after the new release of Fluidd.

Signed-off-by: AntoszHUN <zsikaiantal@gmail.com>

2022-04-25 16:28 UTC, matmen requested changes

2022-04-25 16:28 UTC, matmen commented on src/locales/hu.yaml
> +        látható;<br /><blockquote>fluidd.local, https://192.168.1.150</blockquote>
This doesnt seem right, FluiddPi still defaults to HTTP

2022-04-26 08:19 UTC, pedrolamas approved these changes

2022-04-26 08:21 UTC, matmen approved these changes

2022-04-26 08:27 UTC, merged