nl.yaml
fluidd-core/fluidd pull request #672
Opened 2022-05-14 16:24 UTC by Cyanogenbot

Removed various anglicisms, inconsistencies, and some typos

2022-05-14 22:22 UTC, pedrolamas approved these changes

2022-05-14 22:25 UTC, pedrolamas requested changes
Please add a footer to the main PR comment with a "Signed-off-by" line, following the [CONTRIBUTING](https://github.com/fluidd-core/fluidd/blob/develop/CONTRIBUTING.md) guidelines.

2022-05-17 08:17 UTC, pedrolamas submitted a review, later dismissed

2022-05-17 16:04 UTC, matmen requested changes

2022-05-17 16:04 UTC, matmen commented on src/locales/nl.yaml
> +        password_username: Gebruikersnaam is te lang
this doesn't seem right; the error triggers when the password equals the username, not when the username is too long

2022-05-17 16:04 UTC, matmen commented on src/locales/nl.yaml
> +      upload_file: upload bestand | Bestanden uploaden
Is this correct (order and capitalization)?

2022-05-18 20:41 UTC, matmen commented on src/locales/nl.yaml
> +        password_username: Gebruikersnaam is te lang
"is niet mogelijk" would be fine with me, though the other translations mention the problem directly:
![image](https://user-images.githubusercontent.com/25269274/169152119-f19422d6-8ac8-43e5-907e-f4b20395cf90.png)

2022-05-19 09:34 UTC, pedrolamas approved these changes

2022-05-19 09:36 UTC, pedrolamas approved these changes

2022-05-19 11:34 UTC, matmen approved these changes

2022-05-19 11:40 UTC, merged