fix(layout): move gcode controls to dropdown; fix vertical layout
fluidd-core/fluidd pull request #696
Opened 2022-05-26 12:20 UTC by matmen

Moves the gcode preview related settings to a dropdown and fixes the layout to be compatible with vertical monitors
![image](https://user-images.githubusercontent.com/25269274/170486312-94a65b29-5fd0-4b17-8384-a4a00023eda8.png)
![image](https://user-images.githubusercontent.com/25269274/170486332-93570df0-a29e-4d0d-80b8-5caa71791e61.png)

Not sure if the "Load current file" and "Clear file" buttons should also go there, LMK what you think..

Closes #690

2022-05-26 12:29 UTC, matmen commented
I think the "Load current file" button would fit quite well into the header, like this;
![image](https://user-images.githubusercontent.com/25269274/170487921-e0bdc1db-1039-4497-b7b3-e0c488db5405.png)

2022-05-26 12:58 UTC, pedrolamas commented
> I think the "Load current file" button would fit quite well into the header

I was about to say that I was not very inclined to have those buttons on the dropdown, but this alternative looks really good to me!

I don't have a problem with the preview being that big, but I do get your point! Maybe we make it 16:9 but with a max height?

2022-05-26 13:10 UTC, matmen commented
> I don't have a problem with the preview being that big, but I do get your point! Maybe we make it 16:9 but with a max height?

Sounds good. With a max height of 50% viewport height this would look like this:

Landscape orientation: Whole control still in view, preview not too small
![image](https://user-images.githubusercontent.com/25269274/170493923-1d0ee5e2-a11f-4611-9819-8804cce863df.png)

Portrait orientation: Everything in view, preview filling whole empty space
![image](https://user-images.githubusercontent.com/25269274/170494107-0f511a7e-8cf6-473a-ac8d-b1527f95a61a.png)

2022-05-26 13:50 UTC, pedrolamas commented
@matmen Removing myself from review as this is still on "draft" state.

2022-05-26 15:45 UTC, pedrolamas requested changes
We might want to change the layout for mobile...

![image](https://user-images.githubusercontent.com/85504/170524000-c74faffa-f667-47d9-a6c4-c86024e5710e.png)

Maybe show the layer counters + "clear" button above the controls, or vice versa?

2022-05-26 15:47 UTC, matmen commented on src/components/widgets/gcode-preview/GcodePreviewCard.vue
> +      </app-btn>
Oh yeah, I was using that before, but it collapsed the controls in vertical mode too. I'll add that back

2022-05-26 16:31 UTC, pedrolamas approved these changes

2022-05-26 16:47 UTC, merged

2022-05-29 21:53 UTC, alexrmay91 commented
I know this is already closed and I'm late to the party, but an option (probably best in the main fluid settings) could be "automatically load current file on print start" and "automatically follow progress on file load". If this should be a separate suggestion that can be evaluated for a future milestone, let me know and I'd be happy to type it out.