feat: add icon to shutdown on AppBar
fluidd-core/fluidd pull request #736
Opened 2022-07-03 11:48 UTC by BastelKlug

Closes: #729 

- Shutdown icon on AppBar/TopBar
- Entry in the settings to (de)activate

Here you can see it in action:

https://user-images.githubusercontent.com/44060099/177038146-131b4d90-e044-4868-8f4e-533ad995fa6f.mov

2022-07-03 13:11 UTC, matmen submitted a review, later dismissed
Thanks for your PR! This looks good to me already, though I'm going to mention my UX concerns here again (https://github.com/fluidd-core/fluidd/pull/726#issuecomment-1162354264): Moving the e-stop button conditionally may break its UX (muscle memory wise), though I think it's not too bad in this case (considering the user actively has to toggle it and it doesn't toggle visibility based on an internal state). In the above mentioned PR the button was moved to the left of the e-stop button, but I'm fine with either position in this case, so fully up to you.

2022-07-03 13:51 UTC, pedrolamas requested changes
I wonder if we should be more specific and instead of just "Shutdown" have "Host Shutdown" as that is what it is all about... @matmen what do you think?

2022-07-03 13:53 UTC, pedrolamas commented on src/components/layout/AppBar.vue
> +  }
```suggestion
  async handleHostShutdown () {
    const res = await this.$confirm(
      this.$tc('app.general.simple_form.msg.confirm_shutdown_host'),
      { title: this.$tc('app.general.label.confirm'), color: 'card-heading', icon: '$error' }
    )

    if (res) {
      this.hostShutdown()
    }
  }
```

That `$emit` call should not be needed here (that was on the `SystemCommands.vue` as it probably was needed to dismiss the popup menu, but that is not the case here!

Ideally, I think we should move from `Promise` based code to more modern `async/await` calls, so I went ahead and refactored this method!

2022-07-03 13:56 UTC, matmen commented
> I wonder if we should be more specific and instead of just "Shutdown" have "Host Shutdown" as that is what it is all about...

@pedrolamas Sure, sounds good to me

2022-07-03 21:12 UTC, BastelKlug commented
Thank you for your improvements. 

I have updated the code, so the text looks like this:
<img width="320" alt="Bildschirmfoto 2022-07-03 um 23 12 00" src="https://user-images.githubusercontent.com/44060099/177057393-ff8e915d-f128-4131-acd6-a55e3a25ff5b.png">

2022-07-03 22:08 UTC, pedrolamas approved these changes

2022-07-04 07:13 UTC, merged

2022-07-04 11:13 UTC, Martyfree123 commented
Thank you to @BastelKlug for making my feature request into a reality. This is awesome.

2022-07-04 11:13 UTC, Martyfree123 commented
When will this be included in a stable release?

2022-07-04 11:28 UTC, Martyfree123 commented
Awesome thank you!

2022-07-04 18:08 UTC, matmen commented
Actually @Martyfree123, I just realized your feature request asked for a button to toggle _printer_ power.. This PR added a button to shut down the _host_ (Raspberry Pi), so I think there was some kind of misinterpretation of your FR.. Just to clarify - would you like a toggle button for the `Power` side-bar entries (![image](https://user-images.githubusercontent.com/25269274/177202151-70614271-b108-4f95-8d6f-77d5101a06eb.png))?

2022-07-04 18:09 UTC, Martyfree123 commented
Yes, I was looking for a button to toggle printer power instead of digging into the side bar for it.

2022-07-04 18:11 UTC, Martyfree123 commented
I missed that from the video as well. Damn I was really excited :/