Documents how to properly setup to enable "Exclude Objects"
fluidd-core/fluidd pull request #772
Opened 2022-07-17 07:28 UTC by valadas

Documents how to properly setup to enable "Exclude Objects"

2022-07-17 10:03 UTC, matmen reviewed
Hey, thanks for your PR! I knew I forgot something.. 😅 Looks good to me so far, just one small suggestion:

2022-07-17 16:25 UTC, pedrolamas commented on docs/features/gcode_viewer.md
> +- Add an `[exclude_object]` section to your printer.cfg or fluidd.cfg file.
The fluidd.cfg file contains just the "basics" required by Fluidd to work and nothing else, so I don't think we should add anything else, regardless of impact (if not, why not also add `gcode_arcs`, `sdcard_loop`, ... ?)

Let's leave it out of the basics! 🙂

2022-07-17 16:34 UTC, pedrolamas commented
Thank you for your contribution @valadas.

However, we have [contribution guidelines](https://github.com/fluidd-core/fluidd/blob/develop/CONTRIBUTING.md) that must be followed, specifically "Commit messages should follow the [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/) standard, and should have a Signed-off-by line"

To make things easier, I would ask that you edit your first post on this PR and just add the `Signed-off-by: Your Name <your email address>` footer.

2022-07-18 22:32 UTC, pedrolamas requested changes
Fixed a typo (double "a") and clarified a bit the text.

2022-07-18 22:32 UTC, pedrolamas commented on docs/features/gcode_viewer.md
> +- Add a a line `enable_object_processing: True` to your mooraker.conf `[file_manager]` section.
```suggestion
- Add `enable_object_processing: True` to the `[file_manager]` section in your moonraker.conf file.
```

2022-07-19 06:18 UTC, matmen approved these changes
LGTM

2022-07-19 08:08 UTC, pedrolamas approved these changes

2022-07-19 08:09 UTC, merged