Japanese language update
fluidd-core/fluidd pull request #880
Opened 2022-09-30 07:24 UTC by Suisyan

Japanese language update.
Signed-off-by: Suisyan 99475190+Suisyan@users.noreply.github.com

2022-10-02 21:46 UTC, matmen requested changes

2022-10-02 21:46 UTC, matmen commented on src/locales/ja.yaml
> +      scroll: ''
What's the reason for this change?

2022-10-02 21:46 UTC, matmen commented on src/locales/ja.yaml
> +        https://192.168.1.150</blockquote><br />があります。
Is this intentional?

2022-10-02 21:46 UTC, matmen commented on src/locales/ja.yaml
> +      keyboard_shortcuts: ''
Is this empty translation intentional?

2022-10-02 21:46 UTC, matmen commented on src/locales/ja.yaml
> +      accel_to_decel: Accel to Decel
What's the reason for this change? Seems like it was translated before

2022-10-02 21:46 UTC, matmen commented on src/locales/ja.yaml
> +      add_category: ''
Is this empty translation intentional?

2022-10-02 21:46 UTC, matmen commented on src/locales/ja.yaml
> +      unretract_speed: Unretract Speed
Are these changes intentional? Looks like it was translated before

2022-10-02 21:46 UTC, matmen commented on src/locales/ja.yaml
> +      gcode_preview: 'Gcode Preview [ ベータ版 ]'
This isn't beta anymore.
```suggestion
      gcode_preview: 'Gcode Preview'
```

2022-10-02 21:46 UTC, matmen commented on src/locales/ja.yaml
> +      partial_of_total: '  %{total}の%{partial} '
I don't think this translation should start with whitespaces
```suggestion
      partial_of_total: '%{total}の%{partial} '
```

2022-10-02 21:46 UTC, matmen commented on src/locales/ja.yaml
> +      retract: Firmware Retraction
Is there a reason this key is added but not translated?

2022-10-02 21:46 UTC, matmen commented on src/locales/ja.yaml
> +      dirty: DIRTY
What's the reason for this change?

2022-10-03 18:48 UTC, matmen requested changes

2022-10-03 18:48 UTC, matmen commented on src/locales/ja.yaml
> +        https://192.168.1.150 があります</blockquote>。
```suggestion
        https://192.168.1.150 があります</blockquote>。
```

2022-10-03 18:48 UTC, matmen commented on src/locales/ja.yaml
> +      add_category: ''
This either needs to be removed or translated.

2022-10-05 06:33 UTC, matmen approved these changes
LGTM, but I'd like to keep this open until all other features for 1.21 are merged

2022-10-12 19:54 UTC, matmen commented
@Suisyan Some new translations keys were added with https://github.com/fluidd-core/fluidd/commit/e7106a28fee5c29ac1cc79b0a03f964de344199d, would you be willing to translate those? Thanks!

2022-10-14 09:33 UTC, pedrolamas approved these changes

2022-10-14 13:52 UTC, matmen approved these changes

2022-10-14 13:58 UTC, merged