feat: send on enter
fluidd-core/fluidd pull request #981
Opened 2022-12-15 16:58 UTC by koriwi

tested locally. works as expected

2022-12-15 17:01 UTC, pedrolamas commented
Thank you @koriwi, can you please add a footer to the main PR comment with a "Signed-off-by" line, following the [CONTRIBUTING](https://github.com/fluidd-core/fluidd/blob/develop/CONTRIBUTING.md) guidelines.

Thank you!

2022-12-15 17:36 UTC, koriwi commented
@pedrolamas should be good now

2022-12-15 19:35 UTC, pedrolamas requested changes
This indeed works, though I think an optimal (and consistent with the rest of the codebase) will be encapsulate the `<v-card>` element on with a `<v-form>`, add `@submit.prevent="$emit('click', runCommand)"` to it, and then remove the click handler from the button and set it `type="submit"`

2022-12-15 19:45 UTC, koriwi commented
Will do soon. As I'm not a Vue dev (more or less react) and just changed the steppers on my delta ;)

2022-12-15 20:34 UTC, koriwi commented
done

2022-12-15 22:41 UTC, pedrolamas commented on src/components/ui/AppMacroBtn.vue
> +              @click="$emit('click', runCommand)"
```suggestion
              type="submit"
```

2022-12-15 22:41 UTC, pedrolamas approved these changes

2022-12-16 07:59 UTC, matmen approved these changes

2022-12-16 07:59 UTC, merged